---
layout: page
title: Speaking
permalink: /speaking
---

There is a page when I'm going to keep my public speaking presentations and summaries.

=== Conferences

[cols="^,^,^",options="header"] 
|=======
| Conference | Date | Location
| https://www.meetup.com/Apache-Ignite-Virtual-Meetup/events/273921637/[Apache Ignite Lightning Talks] | October 20, 2020 | Online
| https://dssconf.pl[Data Science Summit] | June 14, 2019 | Warsaw, Poland
|=======

=== Talks

==== Introduction to Apache Ignite ML

Apache Ignite is a distributed in-memory data grid.Apache Ignite Machine Learning (ML) is a set of simple, scalable and efficient tools that allow building predictive machine learning models without costly data transfers.In this presentation we are going to get know Apache Ignite better, look at ML library features and nuances of implementing ML algorithms over distributed data.If you are interested in what can be done if data does not fit into one computerâs memory; you definitely should check out the presentation.

> This talk was given at https://dssconf.pl[Data Science Summit] in Polish

==== What you can learn from your distributed data?

> This talk was given at https://www.meetup.com/Apache-Ignite-Virtual-Meetup/events/273921637/[Apache Ignite Lightning Talks] in English
