# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ravil Galeyev
author:
  name: dehasi
  email: neboskrebb@gmail.com
email: neboskrebb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  There is no unique content.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dehasi.me" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /notes/:title:output_ext

markdown: kramdown
theme: minima
minima:
  social_links:
    twitter: rgaleyev
    github: dehasi
    linkedin: ravil-galeyev-9a7540102

header_pages:
  - headers/projects.md
  - headers/notes.md
  - headers/speaking.md
  - headers/about.md

plugins:
  - jekyll-asciidoc
#  - jekyll-feed

asciidoctor:
  attributes:
    - imagesdir=/assets/images
    - imagesoutdir=/assets/images
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dehasi-src.iml
  - docker_build.sh
  - Makefile
  - git_deploy_key.enc
  - Dockerfile
